version: '3.8'

networks:
  traefik-net:
    external: false

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  test_server:
    container_name: test_server
    image: yeasy/simple-web
    ports:
      - "4000:80"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testy.rule=PathPrefix(`/testy/`)"
      - "traefik.http.routers.testy.entrypoints=web"
      - "traefik.http.services.testy.loadbalancer.server.port=80"

  management:
    container_name: management
    build:
      context: .
    restart: always
    volumes:
      - "/tmp/management-service/docker-compose.yml:/./docker-compose.yml"
    networks:
      - traefik-net
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BASE_PATH=management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.management.rule=PathPrefix(`/management/`)"
      - "traefik.http.routers.management.entrypoints=web"
      - "traefik.http.services.management.loadbalancer.server.port=3000"
