version: '3.8'

services:
  # traefik:
  #   image: traefik:v2.10
  #   container_name: traefik
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=true"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   restart: unless-stopped

  management:
    container_name: management
    build:
      context: .
    restart: always
    volumes:
      - "/tmp/management-service/docker-compose.yml:/./docker-compose.yml"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BASE_PATH=management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.management.rule=PathPrefix(`/management/`)"
      - "traefik.http.routers.management.entrypoints=web"
      - "traefik.http.services.management.loadbalancer.server.url=http://management:3000"
