version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--api.insecure'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  testy:
    container_name: testy
    image: yeasy/simple-web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.testy.rule=PathPrefix(`/testy/`)
      - traefik.http.routers.testy.entrypoints=web
      - traefik.http.services.testy.loadbalancer.server.port=80
      - traefik.http.middlewares.testy.stripprefix.prefixes=/testy